apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-deployment
  annotations:
    kubernetes.io/change-cause: "Initial deployment for Asp.Net"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asp-app
  template:
    metadata:
      name: metak8s
      labels:
        env: prod
        app: asp-app
        app.kubernetes.io/name: asp-app
    spec:
      containers:
        - name: k8s
          image: mcr.microsoft.com/dotnet/samples:aspnetapp
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production"
            - name: OTEL_LOG_LEVEL
              value: "debug"
