apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-app
    group: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_USER
            value: petclinic
          - name: MYSQL_PASSWORD
            value: petclinic
          - name: MYSQL_ROOT_PASSWORD
            value: mysql
          - name: MYSQL_DATABASE
            value: petclinic
        ports:
        - containerPort: 3306
